// <auto-generated />
using Micro.Infra.Data.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Micro.Infra.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230723211224_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Micro.Dominio.Entidades.Programas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alimento")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Aquece")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Instrucoes")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Potencia")
                        .HasColumnType("int");

                    b.Property<int>("Tempo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Programas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alimento = "Pipoca (de micro-ondas)",
                            Aquece = "$",
                            Instrucoes = "Observar o barulho de estouros do milho, caso houver um intervalo de mais de 10 segundos entre um estouro e outro, interrompa o aquecimento.",
                            Nome = "Leite",
                            Potencia = 7,
                            Tempo = 180
                        },
                        new
                        {
                            Id = 2,
                            Alimento = "Leite",
                            Aquece = "*",
                            Instrucoes = "Cuidado com aquecimento de líquidos, o choque térmico aliado ao movimento do recipiente pode causar fervura imediata causando risco de queimaduras.",
                            Nome = "Leite",
                            Potencia = 5,
                            Tempo = 300
                        },
                        new
                        {
                            Id = 3,
                            Alimento = "Carne em pedaço ou fatias",
                            Aquece = "%",
                            Instrucoes = "Interrompa o processo na metade e vire o conteúdo com a parte de baixo para cima para o descongelamento uniforme.",
                            Nome = "Carnes de boi",
                            Potencia = 4,
                            Tempo = 840
                        },
                        new
                        {
                            Id = 4,
                            Alimento = "Frango (qualquer corte)",
                            Aquece = "#",
                            Instrucoes = ": Interrompa o processo na metade e vire o conteúdo com a parte de baixo para cima para o descongelamento uniforme.",
                            Nome = "Frango",
                            Potencia = 7,
                            Tempo = 480
                        },
                        new
                        {
                            Id = 5,
                            Alimento = "Feijão congelado",
                            Aquece = "@",
                            Instrucoes = "Deixe o recipiente destampado e em casos de plástico, cuidado ao retirar o recipiente pois o mesmo pode perder resistência em altas temperaturas.",
                            Nome = "Feijão",
                            Potencia = 9,
                            Tempo = 480
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
